version: "3.9"
   
services:

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      - MYSQL_ROOT_PASSWORD=cae_root_pw
      - MYSQL_HOST=canvas_app_explorer_mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=canvas_app_explorer_local
      - MYSQL_USER=cae_user
      - MYSQL_PASSWORD=cae_pw
    ports:
      - "6306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql:delegated
    container_name: canvas_app_explorer_mysql
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.openshift
      args:
        - TZ=${TZ}
    volumes:
      # Only map the secrets for prod build
      - ${HOME}/mylasecrets:/secrets
    ports:
      - "5000:5000"
    container_name: canvas_app_explorer_prod
    env_file:
      - .env
    environment:
      - DEBUG=False
