// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mXv5TZ5SUPGRneH9RoMn6q
// Component: 4XPgsAhljqdds
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: rgvwcoUrD14Pp/component
import ProductCard from "../../ProductCard"; // plasmic-import: zc_-JZqmkLhAk/component
import Ratings from "../../Ratings"; // plasmic-import: kZJnDl5cN7jJ7/component
import AddRemoveButton from "../../AddRemoveButton"; // plasmic-import: JyIyDBiGW-/component
import Screenshot from "../../Screenshot"; // plasmic-import: fUpKi24Qhx/component
import Footer from "../../Footer"; // plasmic-import: SxuS7aSzfTV9l/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: thj0p9NXEH81i/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_canvas_app_explorer.css"; // plasmic-import: mXv5TZ5SUPGRneH9RoMn6q/projectcss
import "./PlasmicHome.css"; // plasmic-import: 4XPgsAhljqdds/css

export const PlasmicHome__VariantProps = new Array();

export const PlasmicHome__ArgProps = new Array();

function PlasmicHome__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "root_reset_mXv5TZ5SUPGRneH9RoMn6q",
            "Home__root__rfWi8"
          )}
        >
          {false ? (
            <input
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__input",
                "Home__textbox__kcHjj"
              )}
              placeholder={"Some placeholder"}
              size={1}
              type={"text"}
              value={"Some value"}
            />
          ) : null}

          <div
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__div",
              "Home__box___8LuQk"
            )}
          >
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", "Home__header__iXzGr")}
              withSearchBar={"withSearchBar"}
            />

            {false ? (
              <input
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__input",
                  "Home__textbox__y0QeV"
                )}
                placeholder={"Some placeholder"}
                size={1}
                type={"text"}
                value={"Some value"}
              />
            ) : null}

            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Home__box__d20ZQ"
              )}
            >
              <div
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__div",
                  "__wab_text",
                  "Home__box__k3LxN"
                )}
              >
                {
                  "LTI Organizer is a collection of resources to assist the instructor in using the best tools available for you and your students. "
                }
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Home__box___92DMt"
              )}
            >
              <ProductCard
                className={classNames(
                  "__wab_instance",
                  "Home__productCard__foQyr"
                )}
                description={
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__div",
                      "__wab_text",
                      "Home__box__c1Y5M"
                    )}
                  >
                    {"Provides access to the Zoom video conference platform."}
                  </div>
                }
                image={
                  <img
                    alt={""}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__img",
                      "Home__img__zw5Ho"
                    )}
                    role={"img"}
                    src={
                      "/static/plasmic/canvas_app_explorer/images/zoomMeetingpng.png"
                    }
                  />
                }
                logo={
                  <img
                    alt={""}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__img",
                      "Home__img__zZtPf"
                    )}
                    role={"img"}
                    src={
                      "/static/plasmic/canvas_app_explorer/images/zoomLogo.png"
                    }
                  />
                }
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      "Home__ratings__yXulX"
                    )}
                    numReviews={"(45 Review)"}
                    stars={"four"}
                  />
                }
                title={"Zoom"}
                withReviews={"withReviews"}
              >
                <AddRemoveButton
                  className={classNames(
                    "__wab_instance",
                    "Home__addRemoveButton___3D93M"
                  )}
                />
              </ProductCard>

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  "Home__productCard__gpGZx"
                )}
                description={
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__div",
                      "__wab_text",
                      "Home__box__jl7El"
                    )}
                  >
                    {
                      "Dashboard that provides students with information about engagement with course."
                    }
                  </div>
                }
                image={
                  <img
                    alt={""}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__img",
                      "Home__img__psMY"
                    )}
                    role={"img"}
                    src={
                      "/static/plasmic/canvas_app_explorer/images/myLearningAnalytics.png"
                    }
                  />
                }
                logo={
                  <img
                    alt={""}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__img",
                      "Home__img__u0Ib1"
                    )}
                    role={"img"}
                    src={
                      "/static/plasmic/canvas_app_explorer/images/myLaLogo.png"
                    }
                  />
                }
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      "Home__ratings__iUUiJ"
                    )}
                    numReviews={"(45 Review)"}
                    stars={"five"}
                  />
                }
                title={"My Learning Analytics"}
                withReviews={"withReviews"}
              >
                <AddRemoveButton
                  className={classNames(
                    "__wab_instance",
                    "Home__addRemoveButton__bH9Sb"
                  )}
                />
              </ProductCard>

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  "Home__productCard___71L95"
                )}
                description={
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__div",
                      "__wab_text",
                      "Home__box__qBpZp"
                    )}
                  >
                    {
                      "Class discussion/Q&A site with link to course navigation for Piazza discussions."
                    }
                  </div>
                }
                image={
                  <img
                    alt={""}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__img",
                      "Home__img__fApwR"
                    )}
                    role={"img"}
                    src={
                      "/static/plasmic/canvas_app_explorer/images/piazzainstructorpostpng.png"
                    }
                  />
                }
                logo={
                  <img
                    alt={""}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__img",
                      "Home__img__eqcPf"
                    )}
                    role={"img"}
                    src={
                      "/static/plasmic/canvas_app_explorer/images/piazzaLogo.png"
                    }
                  />
                }
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      "Home__ratings___14DWe"
                    )}
                    numReviews={"(45 Review)"}
                    stars={"five"}
                  />
                }
                title={"Piazza"}
                withReviews={"withReviews"}
              >
                <AddRemoveButton
                  className={classNames(
                    "__wab_instance",
                    "Home__addRemoveButton___6ByWv"
                  )}
                  removeToolFromSite={"removeToolFromSite"}
                />
              </ProductCard>

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  "Home__productCard__fdYsT"
                )}
                description={
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__div",
                      "__wab_text",
                      "Home__box__te2Ty"
                    )}
                  >
                    {"Used to record, share, and manage videos."}
                  </div>
                }
                image={
                  <Screenshot
                    data-plasmic-name={"screenshot"}
                    data-plasmic-override={overrides.screenshot}
                    className={classNames(
                      "__wab_instance",
                      "Home__screenshot__th2S7"
                    )}
                  />
                }
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      "Home__ratings__pMbc"
                    )}
                    numReviews={"(45 Review)"}
                    stars={"three"}
                  />
                }
                title={"Panopto"}
                withReviews={"withReviews"}
                withoutScreenshot={"withoutScreenshot"}
              />
            </p.Stack>

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", "Home__footer__sUgvZ")}
            />
          </div>

          {false ? (
            <input
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__input",
                "Home__textbox__triAl"
              )}
              placeholder={"Some placeholder"}
              size={1}
              type={"text"}
              value={"Some value"}
            />
          ) : null}
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "header", "screenshot", "footer"],
  header: ["header"],
  screenshot: ["screenshot"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    screenshot: makeNodeComponent("screenshot"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
