// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mXv5TZ5SUPGRneH9RoMn6q
// Component: tr5phcLQqCoEx
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "../library_plasmic_color_type/plasmic_library_plasmic_color_type.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import "./plasmic_canvas_app_explorer.css"; // plasmic-import: mXv5TZ5SUPGRneH9RoMn6q/projectcss
import "./PlasmicLinkButton.css"; // plasmic-import: tr5phcLQqCoEx/css

export const PlasmicLinkButton__VariantProps = new Array("type", "size");

export const PlasmicLinkButton__ArgProps = new Array("href", "text");

function PlasmicLinkButton__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <a
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "plasmic_default__all",
        "plasmic_default__a",
        "root_reset_mXv5TZ5SUPGRneH9RoMn6q",
        "plasmic_default_styles",
        "plasmic_mixins",
        "plasmic_tokens",
        "plasmic_tokens",
        "LinkButton__root__yNFi",
        {
          LinkButton__rootsize_small__yNFiSQAk: hasVariant(
            variants,
            "size",
            "small"
          ),

          LinkButton__roottype_blankGray__yNFiff2A: hasVariant(
            variants,
            "type",
            "blankGray"
          ),

          LinkButton__roottype_blankOrange__yNFi2KHft: hasVariant(
            variants,
            "type",
            "blankOrange"
          ),

          LinkButton__roottype_outlineGray__yNFiVqldC: hasVariant(
            variants,
            "type",
            "outlineGray"
          ),

          LinkButton__roottype_solidGray__yNFiGiboD: hasVariant(
            variants,
            "type",
            "solidGray"
          ),

          LinkButton__roottype_solidOrange__yNFiI5Pxg: hasVariant(
            variants,
            "type",
            "solidOrange"
          )
        }
      )}
      href={args.href !== undefined ? args.href : "#"}
    >
      {p.renderPlasmicSlot({
        defaultContents: "Do the thing",
        value: args.text,
        className: classNames("LinkButton__slotTargetText__ewQcH", {
          LinkButton__slotTargetTexttype_blankGray__ewQcHff2A: hasVariant(
            variants,
            "type",
            "blankGray"
          ),

          LinkButton__slotTargetTexttype_blankOrange__ewQcH2KHft: hasVariant(
            variants,
            "type",
            "blankOrange"
          ),

          LinkButton__slotTargetTexttype_outlineGray__ewQcHVqldC: hasVariant(
            variants,
            "type",
            "outlineGray"
          ),

          LinkButton__slotTargetTexttype_solidGray__ewQcHGiboD: hasVariant(
            variants,
            "type",
            "solidGray"
          ),

          LinkButton__slotTargetTexttype_solidOrange__ewQcHi5Pxg: hasVariant(
            variants,
            "type",
            "solidOrange"
          )
        })
      })}
    </a>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLinkButton__ArgProps,
      internalVariantPropNames: PlasmicLinkButton__VariantProps
    });

    return PlasmicLinkButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLinkButton";
  } else {
    func.displayName = `PlasmicLinkButton.${nodeName}`;
  }
  return func;
}

export const PlasmicLinkButton = Object.assign(
  // Top-level PlasmicLinkButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicLinkButton
    internalVariantProps: PlasmicLinkButton__VariantProps,
    internalArgProps: PlasmicLinkButton__ArgProps
  }
);

export default PlasmicLinkButton;
/* prettier-ignore-end */
