// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mXv5TZ5SUPGRneH9RoMn6q
// Component: oCDAnWtrIp
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "../library_plasmic_color_type/plasmic_library_plasmic_color_type.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import "./plasmic_canvas_app_explorer.css"; // plasmic-import: mXv5TZ5SUPGRneH9RoMn6q/projectcss
import "./PlasmicTitleLearnMoreButton.css"; // plasmic-import: oCDAnWtrIp/css

export const PlasmicTitleLearnMoreButton__VariantProps = new Array();

export const PlasmicTitleLearnMoreButton__ArgProps = new Array("children");

function PlasmicTitleLearnMoreButton__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "plasmic_default__all",
        "plasmic_default__div",
        "root_reset_mXv5TZ5SUPGRneH9RoMn6q",
        "plasmic_default_styles",
        "plasmic_mixins",
        "plasmic_tokens",
        "plasmic_tokens",
        "TitleLearnMoreButton__root__lnecm"
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: "Find Out More",
        value: args.children,
        className: classNames("TitleLearnMoreButton__slotTargetChildren__riL5Q")
      })}
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTitleLearnMoreButton__ArgProps,
      internalVariantPropNames: PlasmicTitleLearnMoreButton__VariantProps
    });

    return PlasmicTitleLearnMoreButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTitleLearnMoreButton";
  } else {
    func.displayName = `PlasmicTitleLearnMoreButton.${nodeName}`;
  }
  return func;
}

export const PlasmicTitleLearnMoreButton = Object.assign(
  // Top-level PlasmicTitleLearnMoreButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTitleLearnMoreButton
    internalVariantProps: PlasmicTitleLearnMoreButton__VariantProps,
    internalArgProps: PlasmicTitleLearnMoreButton__ArgProps
  }
);

export default PlasmicTitleLearnMoreButton;
/* prettier-ignore-end */
