// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mXv5TZ5SUPGRneH9RoMn6q
// Component: 4XPgsAhljqdds
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: rgvwcoUrD14Pp/component
import ProductCard from "../../ProductCard"; // plasmic-import: zc_-JZqmkLhAk/component
import Ratings from "../../Ratings"; // plasmic-import: kZJnDl5cN7jJ7/component
import AddRemoveButton from "../../AddRemoveButton"; // plasmic-import: JyIyDBiGW-/component
import LearnMoreButton from "../../LearnMoreButton"; // plasmic-import: dm73fzeGC7/component
import Footer from "../../Footer"; // plasmic-import: SxuS7aSzfTV9l/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: thj0p9NXEH81i/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_canvas_app_explorer.css"; // plasmic-import: mXv5TZ5SUPGRneH9RoMn6q/projectcss
import "./PlasmicHome.css"; // plasmic-import: 4XPgsAhljqdds/css

export const PlasmicHome__VariantProps = new Array();

export const PlasmicHome__ArgProps = new Array();

function PlasmicHome__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "root_reset_mXv5TZ5SUPGRneH9RoMn6q",
            "Home__root__rfWi8"
          )}
        >
          {false ? (
            <input
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__input",
                "Home__textbox__kcHjj"
              )}
              placeholder={"Some placeholder"}
              size={1}
              type={"text"}
              value={"Some value"}
            />
          ) : null}

          <div
            data-plasmic-name={"appContainer"}
            data-plasmic-override={overrides.appContainer}
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__div",
              "Home__appContainer___8LuQk"
            )}
          >
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", "Home__header__iXzGr")}
              noSearchBarOrSettings={"noSearchBarOrSettings"}
            />

            {false ? (
              <input
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__input",
                  "Home__textbox__y0QeV"
                )}
                placeholder={"Some placeholder"}
                size={1}
                type={"text"}
                value={"Some value"}
              />
            ) : null}

            <div
              data-plasmic-name={"caeDescriptionContainer"}
              data-plasmic-override={overrides.caeDescriptionContainer}
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Home__caeDescriptionContainer__d20ZQ"
              )}
            >
              <div
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__div",
                  "__wab_text",
                  "Home__freeBox__k3LxN"
                )}
              >
                {
                  "Canvas App Explorer is a collection of resources to assist the instructor in using the best tools available for you and your students. "
                }
              </div>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"productCardContainer"}
              data-plasmic-override={overrides.productCardContainer}
              hasGap={true}
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "Home__productCardContainer___92DMt"
              )}
            >
              <ProductCard
                data-plasmic-name={"zoomCard"}
                data-plasmic-override={overrides.zoomCard}
                addRemoveSlot={
                  <AddRemoveButton
                    className={classNames(
                      "__wab_instance",
                      "Home__addRemoveButton___3D93M"
                    )}
                  />
                }
                className={classNames(
                  "__wab_instance",
                  "Home__zoomCard__foQyr"
                )}
                description={
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__div",
                      "__wab_text",
                      "Home__freeBox__c1Y5M"
                    )}
                  >
                    {"Provides access to the Zoom video conference platform."}
                  </div>
                }
                descriptionLearnMore={
                  <span>
                    <span style={{ fontWeight: 700 }}>{"Description"}</span>
                    <React.Fragment>
                      {
                        "\nProvides access to the Zoom video conference platform."
                      }
                    </React.Fragment>
                  </span>
                }
                image={
                  <img
                    alt={""}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__img",
                      "Home__img__zw5Ho"
                    )}
                    role={"img"}
                    src={
                      "/static/plasmic/canvas_app_explorer/images/zoomMeetingpng.png"
                    }
                  />
                }
                learnMoreSlot={
                  <LearnMoreButton
                    data-plasmic-name={"learnMoreButton"}
                    data-plasmic-override={overrides.learnMoreButton}
                    className={classNames(
                      "__wab_instance",
                      "Home__learnMoreButton__j6ASy"
                    )}
                  />
                }
                logo={
                  <img
                    alt={""}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__img",
                      "Home__img__zZtPf"
                    )}
                    role={"img"}
                    src={
                      "/static/plasmic/canvas_app_explorer/images/zoomLogo.png"
                    }
                  />
                }
                onlyLearnMore={"onlyLearnMore"}
                placementsInCanvasLearnMore={
                  <span>
                    <span style={{ fontWeight: 700 }}>
                      {"Placements in Canvas"}
                    </span>
                    <React.Fragment>{"\nCourse Navigation"}</React.Fragment>
                  </span>
                }
                privacyAgreementLearnMore={
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__div",
                      "__wab_text",
                      "Home__freeBox__pkIjF"
                    )}
                  >
                    <span>
                      <span style={{ fontWeight: 700 }}>
                        {"Privacy Agreement"}
                      </span>
                      <React.Fragment>
                        {"\nData Protection Addendum\n"}
                      </React.Fragment>
                    </span>
                  </div>
                }
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      "Home__ratings__yXulX"
                    )}
                    numReviews={"(45 Review)"}
                    stars={"four"}
                  />
                }
                supportResourcesLearnMore={
                  <span>
                    <span style={{ fontWeight: 700 }}>
                      {"Support Resources"}
                    </span>
                    <React.Fragment>
                      {"\nITS Teaching with Zoom Guide"}
                    </React.Fragment>
                  </span>
                }
                title={"Zoom"}
                toolLearnMore={
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__div",
                      "__wab_text",
                      "Home__freeBox__dHRrw"
                    )}
                  >
                    <span>
                      <span style={{ fontWeight: 700 }}>{"Tool"}</span>
                      <React.Fragment>{"\nZoom"}</React.Fragment>
                    </span>
                  </div>
                }
              />

              <ProductCard
                data-plasmic-name={"myLaCard"}
                data-plasmic-override={overrides.myLaCard}
                addRemoveSlot={
                  <AddRemoveButton
                    className={classNames(
                      "__wab_instance",
                      "Home__addRemoveButton__bH9Sb"
                    )}
                  />
                }
                className={classNames(
                  "__wab_instance",
                  "Home__myLaCard__gpGZx"
                )}
                description={
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__div",
                      "__wab_text",
                      "Home__freeBox__jl7El"
                    )}
                  >
                    {
                      "Dashboard that provides students with information about engagement with course."
                    }
                  </div>
                }
                descriptionLearnMore={
                  <span>
                    <span style={{ fontWeight: 700 }}>{"Description"}</span>
                    <React.Fragment>
                      {
                        "\nMy Learning Analytics (MyLA) is a dashboard that provides students with information about their engagement with course materials and resources, assignments, and grades in a Canvas course."
                      }
                    </React.Fragment>
                  </span>
                }
                image={
                  <img
                    alt={""}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__img",
                      "Home__img__psMY"
                    )}
                    role={"img"}
                    src={
                      "/static/plasmic/canvas_app_explorer/images/myLearningAnalytics.png"
                    }
                  />
                }
                logo={
                  <img
                    alt={""}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__img",
                      "Home__img__u0Ib1"
                    )}
                    role={"img"}
                    src={
                      "/static/plasmic/canvas_app_explorer/images/myLaLogo.png"
                    }
                  />
                }
                onlyLearnMore={"onlyLearnMore"}
                placementsInCanvasLearnMore={
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__div",
                      "__wab_text",
                      "Home__freeBox__vTgLe"
                    )}
                  >
                    <span>
                      <span style={{ fontWeight: 700 }}>
                        {"Placements in Canvas"}
                      </span>
                      <React.Fragment>{"\nCourse Navigation"}</React.Fragment>
                    </span>
                  </div>
                }
                privacyAgreementLearnMore={
                  <span>
                    <span style={{ fontWeight: 700 }}>
                      {"Privacy Agreement"}
                    </span>
                    <React.Fragment>
                      {"\nNot required (U-M hosted)"}
                    </React.Fragment>
                  </span>
                }
                ratings={
                  true ? (
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        "Home__ratings__iUUiJ"
                      )}
                      numReviews={"(45 Review)"}
                      stars={"five"}
                    />
                  ) : null
                }
                supportResourcesLearnMore={
                  <span>
                    <span style={{ fontWeight: 700 }}>
                      {"Support Resources"}
                    </span>
                    <React.Fragment>
                      {"\nITS My Learning Analytics Guide"}
                    </React.Fragment>
                  </span>
                }
                title={"My Learning Analytics"}
                toolLearnMore={
                  <span>
                    <span style={{ fontWeight: 700 }}>{"Tool"}</span>
                    <React.Fragment>{"\nMy Learning Analytics"}</React.Fragment>
                  </span>
                }
              />

              <ProductCard
                data-plasmic-name={"piazzaCard"}
                data-plasmic-override={overrides.piazzaCard}
                addRemoveSlot={
                  <AddRemoveButton
                    className={classNames(
                      "__wab_instance",
                      "Home__addRemoveButton___6ByWv"
                    )}
                    removeToolFromSite={"removeToolFromSite"}
                  />
                }
                className={classNames(
                  "__wab_instance",
                  "Home__piazzaCard___71L95"
                )}
                description={
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__div",
                      "__wab_text",
                      "Home__freeBox__qBpZp"
                    )}
                  >
                    {
                      "Class discussion/Q&A site with link to course navigation for Piazza discussions."
                    }
                  </div>
                }
                descriptionLearnMore={
                  <span>
                    <span style={{ fontWeight: 700 }}>{"Description"}</span>
                    <React.Fragment>
                      {
                        "\nPiazza is a new style of discussion/Q&A site with a focus on educational institutions. This integration adds a link to the course navigation for Piazza discussions, and auto-logs the user into the course discussions area."
                      }
                    </React.Fragment>
                  </span>
                }
                image={
                  <img
                    alt={""}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__img",
                      "Home__img__fApwR"
                    )}
                    role={"img"}
                    src={
                      "/static/plasmic/canvas_app_explorer/images/piazzainstructorpostpng.png"
                    }
                  />
                }
                logo={
                  <img
                    alt={""}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__img",
                      "Home__img__eqcPf"
                    )}
                    role={"img"}
                    src={
                      "/static/plasmic/canvas_app_explorer/images/piazzaLogo.png"
                    }
                  />
                }
                onlyLearnMore={"onlyLearnMore"}
                placementsInCanvasLearnMore={
                  <span>
                    <span style={{ fontWeight: 700 }}>
                      {"Placements in Canvas"}
                    </span>
                    <React.Fragment>{"\nCourse Navigation"}</React.Fragment>
                  </span>
                }
                privacyAgreementLearnMore={
                  <span>
                    <span style={{ fontWeight: 700 }}>
                      {"Privacy Agreement"}
                    </span>
                    <React.Fragment>
                      {"\nData Protection Addendum"}
                    </React.Fragment>
                  </span>
                }
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      "Home__ratings___14DWe"
                    )}
                    numReviews={"(45 Review)"}
                    stars={"five"}
                  />
                }
                supportResourcesLearnMore={
                  <span>
                    <span style={{ fontWeight: 700 }}>
                      {"Support Resources"}
                    </span>
                    <React.Fragment>{"\nPiazza Support"}</React.Fragment>
                  </span>
                }
                title={"Piazza"}
                toolLearnMore={
                  <span>
                    <span style={{ fontWeight: 700 }}>{"Tool"}</span>
                    <React.Fragment>{"\nPiazza"}</React.Fragment>
                  </span>
                }
              />

              <ProductCard
                data-plasmic-name={"panoptoCard"}
                data-plasmic-override={overrides.panoptoCard}
                className={classNames(
                  "__wab_instance",
                  "Home__panoptoCard__cv5Of"
                )}
                description={
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__div",
                      "__wab_text",
                      "Home__freeBox__p0Nci"
                    )}
                  >
                    {"Panopto is used to record, share and manage videos."}
                  </div>
                }
                learnMore={"learnMore"}
                title={"Panopto"}
              />
            </p.Stack>

            {true ? (
              <Footer
                data-plasmic-name={"footer"}
                data-plasmic-override={overrides.footer}
                className={classNames("__wab_instance", "Home__footer__sUgvZ")}
              />
            ) : null}
          </div>

          {false ? (
            <input
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__input",
                "Home__textbox__triAl"
              )}
              placeholder={"Some placeholder"}
              size={1}
              type={"text"}
              value={"Some value"}
            />
          ) : null}
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "appContainer",
    "header",
    "caeDescriptionContainer",
    "productCardContainer",
    "zoomCard",
    "learnMoreButton",
    "myLaCard",
    "piazzaCard",
    "panoptoCard",
    "footer"
  ],

  appContainer: [
    "appContainer",
    "header",
    "caeDescriptionContainer",
    "productCardContainer",
    "zoomCard",
    "learnMoreButton",
    "myLaCard",
    "piazzaCard",
    "panoptoCard",
    "footer"
  ],

  header: ["header"],
  caeDescriptionContainer: ["caeDescriptionContainer"],
  productCardContainer: [
    "productCardContainer",
    "zoomCard",
    "learnMoreButton",
    "myLaCard",
    "piazzaCard",
    "panoptoCard"
  ],

  zoomCard: ["zoomCard", "learnMoreButton"],
  learnMoreButton: ["learnMoreButton"],
  myLaCard: ["myLaCard"],
  piazzaCard: ["piazzaCard"],
  panoptoCard: ["panoptoCard"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    appContainer: makeNodeComponent("appContainer"),
    header: makeNodeComponent("header"),
    caeDescriptionContainer: makeNodeComponent("caeDescriptionContainer"),
    productCardContainer: makeNodeComponent("productCardContainer"),
    zoomCard: makeNodeComponent("zoomCard"),
    learnMoreButton: makeNodeComponent("learnMoreButton"),
    myLaCard: makeNodeComponent("myLaCard"),
    piazzaCard: makeNodeComponent("piazzaCard"),
    panoptoCard: makeNodeComponent("panoptoCard"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
