// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mXv5TZ5SUPGRneH9RoMn6q
// Component: fUpKi24Qhx
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "../library_plasmic_color_type/plasmic_library_plasmic_color_type.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import "./plasmic_canvas_app_explorer.css"; // plasmic-import: mXv5TZ5SUPGRneH9RoMn6q/projectcss
import "./PlasmicScreenshot.css"; // plasmic-import: fUpKi24Qhx/css

export const PlasmicScreenshot__VariantProps = new Array();

export const PlasmicScreenshot__ArgProps = new Array();

function PlasmicScreenshot__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <img
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      alt={""}
      className={classNames(
        "plasmic_default__all",
        "plasmic_default__img",
        "root_reset_mXv5TZ5SUPGRneH9RoMn6q",
        "plasmic_default_styles",
        "plasmic_mixins",
        "plasmic_tokens",
        "plasmic_tokens",
        "Screenshot__root__mhd7D"
      )}
      src={
        "/static/plasmic/canvas_app_explorer/images/panoptoVideoPlatformInVideoQuizzing1280X662Jpg.jpeg"
      }
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicScreenshot__ArgProps,
      internalVariantPropNames: PlasmicScreenshot__VariantProps
    });

    return PlasmicScreenshot__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicScreenshot";
  } else {
    func.displayName = `PlasmicScreenshot.${nodeName}`;
  }
  return func;
}

export const PlasmicScreenshot = Object.assign(
  // Top-level PlasmicScreenshot renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicScreenshot
    internalVariantProps: PlasmicScreenshot__VariantProps,
    internalArgProps: PlasmicScreenshot__ArgProps
  }
);

export default PlasmicScreenshot;
/* prettier-ignore-end */
