// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mXv5TZ5SUPGRneH9RoMn6q
// Component: dm73fzeGC7
import * as React from "react";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_canvas_app_explorer.css"; // plasmic-import: mXv5TZ5SUPGRneH9RoMn6q/projectcss
import "./PlasmicLearnMoreButton.css"; // plasmic-import: dm73fzeGC7/css

export const PlasmicLearnMoreButton__VariantProps = new Array("learnMore");

export const PlasmicLearnMoreButton__ArgProps = new Array();

function PlasmicLearnMoreButton__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (hasVariant(variants, "learnMore", "learnMore") ? false : true) ? (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "plasmic_default__all",
        "plasmic_default__div",
        "__wab_text",
        "root_reset_mXv5TZ5SUPGRneH9RoMn6q",
        "LearnMoreButton__root__njoaf",
        {
          LearnMoreButton__root__learnMore__njoaFb6N26: hasVariant(
            variants,
            "learnMore",
            "learnMore"
          )
        }
      )}
    >
      {"Learn More"}
    </div>
  ) : null;
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLearnMoreButton__ArgProps,
      internalVariantPropNames: PlasmicLearnMoreButton__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicLearnMoreButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLearnMoreButton";
  } else {
    func.displayName = `PlasmicLearnMoreButton.${nodeName}`;
  }
  return func;
}

export const PlasmicLearnMoreButton = Object.assign(
  // Top-level PlasmicLearnMoreButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicLearnMoreButton
    internalVariantProps: PlasmicLearnMoreButton__VariantProps,
    internalArgProps: PlasmicLearnMoreButton__ArgProps
  }
);

export default PlasmicLearnMoreButton;
/* prettier-ignore-end */
