// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mXv5TZ5SUPGRneH9RoMn6q
// Component: I3rygGi43X
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_canvas_app_explorer.css"; // plasmic-import: mXv5TZ5SUPGRneH9RoMn6q/projectcss
import "./PlasmicLearnMoreCard.css"; // plasmic-import: I3rygGi43X/css

export const PlasmicLearnMoreCard__VariantProps = new Array();

export const PlasmicLearnMoreCard__ArgProps = new Array();

function PlasmicLearnMoreCard__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "plasmic_default__all",
        "plasmic_default__div",
        "root_reset_mXv5TZ5SUPGRneH9RoMn6q",
        "LearnMoreCard__root__voRrI"
      )}
    >
      <div
        className={classNames(
          "plasmic_default__all",
          "plasmic_default__div",
          "LearnMoreCard__box__w6Dx1"
        )}
      >
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "__wab_text",
            "LearnMoreCard__box__qw270"
          )}
        >
          <span>
            <span style={{ fontWeight: 700 }}>{"Tool"}</span>
            <React.Fragment>{"\nZoom\n"}</React.Fragment>
          </span>
        </div>

        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "__wab_text",
            "LearnMoreCard__box__o9T3"
          )}
        >
          <span>
            <span style={{ fontWeight: 700 }}>{"Description"}</span>
            <React.Fragment>
              {"\nProvides access to the Zoom video conference platform.\n"}
            </React.Fragment>
          </span>
        </div>

        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "__wab_text",
            "LearnMoreCard__box___7N0Lr"
          )}
        >
          <span>
            <span style={{ fontWeight: 700 }}>{"Privacy Agreement"}</span>
            <React.Fragment>{"\nData Protection Addendum\n"}</React.Fragment>
          </span>
        </div>

        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "__wab_text",
            "LearnMoreCard__box___4Fl3"
          )}
        >
          <span>
            <span style={{ fontWeight: 700 }}>{"Placements in Canvas"}</span>
            <React.Fragment>{"\nCourse Navigation\n"}</React.Fragment>
          </span>
        </div>

        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "__wab_text",
            "LearnMoreCard__box__amH9"
          )}
        >
          <span>
            <span style={{ fontWeight: 700 }}>{"Support Resources"}</span>
            <React.Fragment>
              {"\nITS Teaching with Zoom Guide (would be link)"}
            </React.Fragment>
          </span>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLearnMoreCard__ArgProps,
      internalVariantPropNames: PlasmicLearnMoreCard__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicLearnMoreCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLearnMoreCard";
  } else {
    func.displayName = `PlasmicLearnMoreCard.${nodeName}`;
  }
  return func;
}

export const PlasmicLearnMoreCard = Object.assign(
  // Top-level PlasmicLearnMoreCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicLearnMoreCard
    internalVariantProps: PlasmicLearnMoreCard__VariantProps,
    internalArgProps: PlasmicLearnMoreCard__ArgProps
  }
);

export default PlasmicLearnMoreCard;
/* prettier-ignore-end */
