// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mXv5TZ5SUPGRneH9RoMn6q
// Component: zc_-JZqmkLhAk
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import LearnMoreTool from "../../LearnMoreTool"; // plasmic-import: 50HKxnb8xJ/component
import ScreenshotBackground from "../../ScreenshotBackground"; // plasmic-import: pi3PBoRiWhk/component
import Ratings from "../../Ratings"; // plasmic-import: kZJnDl5cN7jJ7/component
import LinkButton from "../../LinkButton"; // plasmic-import: tr5phcLQqCoEx/component
import AddRemoveButton from "../../AddRemoveButton"; // plasmic-import: JyIyDBiGW-/component
import LearnMoreButton from "../../LearnMoreButton"; // plasmic-import: dm73fzeGC7/component
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_canvas_app_explorer.css"; // plasmic-import: mXv5TZ5SUPGRneH9RoMn6q/projectcss
import "./PlasmicProductCard.css"; // plasmic-import: zc_-JZqmkLhAk/css

export const PlasmicProductCard__VariantProps = new Array(
  "withReviews",
  "withoutScreenshot",
  "learnMore"
);

export const PlasmicProductCard__ArgProps = new Array(
  "title",
  "image",
  "ratings",
  "logo",
  "description",
  "addRemoveButton",
  "toolLearnMore",
  "descriptionLearnMore",
  "privacyAgreementLearnMore",
  "placementsInCanvasLearnMore",
  "supportResourcesLearnMore",
  "learnMoreButton"
);

function PlasmicProductCard__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        "plasmic_default__all",
        "plasmic_default__div",
        "root_reset_mXv5TZ5SUPGRneH9RoMn6q",
        "ProductCard__root___1U08P",
        {
          ProductCard__root__learnMore___1U08POklBv: hasVariant(
            variants,
            "learnMore",
            "learnMore"
          ),

          ProductCard__root__withReviews___1U08PvvVo9: hasVariant(
            variants,
            "withReviews",
            "withReviews"
          ),

          ProductCard__root__withoutScreenshot___1U08PUtYkz: hasVariant(
            variants,
            "withoutScreenshot",
            "withoutScreenshot"
          )
        }
      )}
    >
      {false ? (
        <LearnMoreTool
          data-plasmic-name={"learnMoreTool"}
          data-plasmic-override={overrides.learnMoreTool}
          className={classNames(
            "__wab_instance",
            "ProductCard__learnMoreTool__uqWdz"
          )}
        />
      ) : null}
      {false ? (
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "ProductCard__box__fjr2W"
          )}
        >
          {false ? (
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "__wab_text",
                "ProductCard__box__kpIdU"
              )}
            >
              {"Enter some text"}
            </div>
          ) : null}
        </div>
      ) : null}
      {false ? (
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "ProductCard__box__fGeZt"
          )}
        >
          {false ? (
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "__wab_text",
                "ProductCard__box__t9Ot"
              )}
            >
              {"Enter some text"}
            </div>
          ) : null}
        </div>
      ) : null}
      {false ? (
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "ProductCard__box__pdlFp"
          )}
        >
          {false ? (
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "__wab_text",
                "ProductCard__box__pcpps"
              )}
            >
              {"Enter some text"}
            </div>
          ) : null}
        </div>
      ) : null}
      {false ? (
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "ProductCard__box___5MRxG"
          )}
        >
          {false ? (
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "__wab_text",
                "ProductCard__box__tCd2V"
              )}
            >
              {"Enter some text"}
            </div>
          ) : null}
        </div>
      ) : null}
      {false ? (
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "ProductCard__box__oShwi"
          )}
        >
          {false ? (
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "__wab_text",
                "ProductCard__box__wABx5"
              )}
            >
              {"Enter some text"}
            </div>
          ) : null}
        </div>
      ) : null}
      {(hasVariant(variants, "learnMore", "learnMore") ? false : true) ? (
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "ProductCard__box__l71Vb",
            {
              ProductCard__box__learnMore__l71VbOklBv: hasVariant(
                variants,
                "learnMore",
                "learnMore"
              ),

              ProductCard__box__withReviews__l71VBvvVo9: hasVariant(
                variants,
                "withReviews",
                "withReviews"
              )
            }
          )}
        >
          {(hasVariant(variants, "learnMore", "learnMore") ? false : true) ? (
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "ProductCard__box__hJJoE",
                {
                  ProductCard__box__learnMore__hJJoEOklBv: hasVariant(
                    variants,
                    "learnMore",
                    "learnMore"
                  )
                }
              )}
            >
              {(hasVariant(variants, "learnMore", "learnMore") ? false : true)
                ? p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__img",
                          "ProductCard__img___0SrCv"
                        )}
                        role={"img"}
                        src={
                          "/static/plasmic/canvas_app_explorer/images/panoptoLogo2.png"
                        }
                      />
                    ),

                    value: args.logo
                  })
                : null}
            </div>
          ) : null}
        </div>
      ) : null}
      {(hasVariant(variants, "learnMore", "learnMore") ? false : true)
        ? p.renderPlasmicSlot({
            defaultContents:
              "Panopto is used to record, share and manage videos.",
            value: args.description
          })
        : null}
      {(hasVariant(variants, "learnMore", "learnMore") ? false : true) ? (
        <ScreenshotBackground
          data-plasmic-name={"screenshotBackground"}
          data-plasmic-override={overrides.screenshotBackground}
          className={classNames(
            "__wab_instance",
            "ProductCard__screenshotBackground__gjUdG",
            {
              ProductCard__screenshotBackground__learnMore__gjUdGOklBv:
                hasVariant(variants, "learnMore", "learnMore"),
              ProductCard__screenshotBackground__withReviews__gjUdGvvVo9:
                hasVariant(variants, "withReviews", "withReviews"),
              ProductCard__screenshotBackground__withoutScreenshot__gjUdGutYkz:
                hasVariant(variants, "withoutScreenshot", "withoutScreenshot")
            }
          )}
          image={p.renderPlasmicSlot({
            defaultContents: (
              <img
                alt={""}
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__img",
                  "ProductCard__img__z4Zz"
                )}
                role={"img"}
                src={"/static/plasmic/canvas_app_explorer/images/panopto.png"}
              />
            ),

            value: args.image,
            className: classNames("ProductCard__slotImage__bjvkn", {
              ProductCard__slotImage__withoutScreenshot__bjvknutYkz: hasVariant(
                variants,
                "withoutScreenshot",
                "withoutScreenshot"
              )
            })
          })}
        />
      ) : null}
      {(hasVariant(variants, "withReviews", "withReviews") ? true : false)
        ? p.renderPlasmicSlot({
            defaultContents: (
              <Ratings
                className={classNames(
                  "__wab_instance",
                  "ProductCard__ratings__yXQd"
                )}
              />
            ),

            value: args.ratings
          })
        : null}
      {(hasVariant(variants, "learnMore", "learnMore") ? false : true) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "ProductCard__box__sbbu9",
            {
              ProductCard__box__learnMore__sbbu9OklBv: hasVariant(
                variants,
                "learnMore",
                "learnMore"
              )
            }
          )}
        >
          {(hasVariant(variants, "learnMore", "learnMore") ? false : true)
            ? p.renderPlasmicSlot({
                defaultContents: "Title",
                value: args.title,
                className: classNames("ProductCard__slotTitle__kXepm", {
                  ProductCard__slotTitle__learnMore__kXepmOklBv: hasVariant(
                    variants,
                    "learnMore",
                    "learnMore"
                  )
                })
              })
            : null}
        </p.Stack>
      ) : null}
      {(hasVariant(variants, "learnMore", "learnMore") ? true : false) ? (
        <img
          alt={""}
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__img",
            "ProductCard__img__vbid0",
            {
              ProductCard__img__learnMore__vbid0OklBv: hasVariant(
                variants,
                "learnMore",
                "learnMore"
              )
            }
          )}
          role={"img"}
          src={
            hasVariant(variants, "learnMore", "learnMore")
              ? "/static/plasmic/canvas_app_explorer/images/zoom.png"
              : undefined
          }
        />
      ) : null}

      <div
        className={classNames(
          "plasmic_default__all",
          "plasmic_default__div",
          "ProductCard__box__wMuGj",
          {
            ProductCard__box__learnMore__wMuGjOklBv: hasVariant(
              variants,
              "learnMore",
              "learnMore"
            )
          }
        )}
      >
        {(hasVariant(variants, "learnMore", "learnMore") ? false : true) ? (
          <LinkButton
            className={classNames(
              "__wab_instance",
              "ProductCard__linkButton__cT7H",
              {
                ProductCard__linkButton__learnMore__cT7HOklBv: hasVariant(
                  variants,
                  "learnMore",
                  "learnMore"
                ),

                ProductCard__linkButton__withoutScreenshot__cT7HUtYkz:
                  hasVariant(variants, "withoutScreenshot", "withoutScreenshot")
              }
            )}
            text={p.renderPlasmicSlot({
              defaultContents: (
                <AddRemoveButton
                  className={classNames(
                    "__wab_instance",
                    "ProductCard__addRemoveButton___794LZ"
                  )}
                  removeToolFromSite={"removeToolFromSite"}
                />
              ),

              value: args.addRemoveButton
            })}
          />
        ) : null}

        <LinkButton
          className={classNames(
            "__wab_instance",
            "ProductCard__linkButton__cX8QG",
            {
              ProductCard__linkButton__withoutScreenshot__cX8QGutYkz:
                hasVariant(variants, "withoutScreenshot", "withoutScreenshot")
            }
          )}
          text={p.renderPlasmicSlot({
            defaultContents: (
              <LearnMoreButton
                className={classNames(
                  "__wab_instance",
                  "ProductCard__learnMoreButton___0AuCk"
                )}
              />
            ),

            value: args.learnMoreButton
          })}
        />
      </div>

      {false ? (
        <img
          alt={""}
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__img",
            "ProductCard__img__bTZld"
          )}
          role={"img"}
        />
      ) : null}
      {(hasVariant(variants, "learnMore", "learnMore") ? false : false) ? (
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "ProductCard__box__aSszv",
            {
              ProductCard__box__learnMore__aSszvOklBv: hasVariant(
                variants,
                "learnMore",
                "learnMore"
              )
            }
          )}
        >
          {false ? (
            <div
              className={classNames(
                "plasmic_default__all",
                "plasmic_default__div",
                "__wab_text",
                "ProductCard__box__bjM9S"
              )}
            >
              {"Enter some text"}
            </div>
          ) : null}
        </div>
      ) : null}
      {(hasVariant(variants, "learnMore", "learnMore") ? true : false) ? (
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "ProductCard__box__pggEe",
            {
              ProductCard__box__learnMore__pggEeOklBv: hasVariant(
                variants,
                "learnMore",
                "learnMore"
              )
            }
          )}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <span>
                <span style={{ fontWeight: 700 }}>{"Tool"}</span>
                <React.Fragment>{"\nZoom"}</React.Fragment>
              </span>
            ),

            value: args.toolLearnMore
          })}
        </div>
      ) : null}
      {(hasVariant(variants, "learnMore", "learnMore") ? true : false) ? (
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "ProductCard__box___0HGbF",
            {
              ProductCard__box__learnMore___0HGbFOklBv: hasVariant(
                variants,
                "learnMore",
                "learnMore"
              )
            }
          )}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <span>
                <span style={{ fontWeight: 700 }}>{"Description"}</span>
                <React.Fragment>
                  {"\nProvides access to the Zoom video conference platform"}
                </React.Fragment>
              </span>
            ),

            value: args.descriptionLearnMore
          })}
        </div>
      ) : null}
      {(hasVariant(variants, "learnMore", "learnMore") ? true : false) ? (
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "ProductCard__box__vBf2M",
            {
              ProductCard__box__learnMore__vBf2MOklBv: hasVariant(
                variants,
                "learnMore",
                "learnMore"
              )
            }
          )}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <span>
                <span style={{ fontWeight: 700 }}>{"Privacy Agreement"}</span>
                <React.Fragment>{"\nData Protection Addendum"}</React.Fragment>
              </span>
            ),

            value: args.privacyAgreementLearnMore
          })}
        </div>
      ) : null}
      {(hasVariant(variants, "learnMore", "learnMore") ? true : false) ? (
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "ProductCard__box__emvgm",
            {
              ProductCard__box__learnMore__emvgmOklBv: hasVariant(
                variants,
                "learnMore",
                "learnMore"
              )
            }
          )}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <span>
                <span style={{ fontWeight: 700 }}>
                  {"Placements in Canvas"}
                </span>
                <React.Fragment>{"\nCourse Navigation"}</React.Fragment>
              </span>
            ),

            value: args.placementsInCanvasLearnMore
          })}
        </div>
      ) : null}
      {(hasVariant(variants, "learnMore", "learnMore") ? true : false) ? (
        <div
          className={classNames(
            "plasmic_default__all",
            "plasmic_default__div",
            "ProductCard__box__wfCuQ",
            {
              ProductCard__box__learnMore__wfCuQOklBv: hasVariant(
                variants,
                "learnMore",
                "learnMore"
              )
            }
          )}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <span>
                <span style={{ fontWeight: 700 }}>{"Support Resources"}</span>
                <React.Fragment>
                  {"\nITS Teaching with Zoom Guide (link)"}
                </React.Fragment>
              </span>
            ),

            value: args.supportResourcesLearnMore
          })}
        </div>
      ) : null}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "learnMoreTool", "screenshotBackground"],
  learnMoreTool: ["learnMoreTool"],
  screenshotBackground: ["screenshotBackground"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicProductCard__ArgProps,
      internalVariantPropNames: PlasmicProductCard__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicProductCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProductCard";
  } else {
    func.displayName = `PlasmicProductCard.${nodeName}`;
  }
  return func;
}

export const PlasmicProductCard = Object.assign(
  // Top-level PlasmicProductCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    learnMoreTool: makeNodeComponent("learnMoreTool"),
    screenshotBackground: makeNodeComponent("screenshotBackground"),
    // Metadata about props expected for PlasmicProductCard
    internalVariantProps: PlasmicProductCard__VariantProps,
    internalArgProps: PlasmicProductCard__ArgProps
  }
);

export default PlasmicProductCard;
/* prettier-ignore-end */
