// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mXv5TZ5SUPGRneH9RoMn6q
// Component: kZJnDl5cN7jJ7
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "../library_plasmic_color_type/plasmic_library_plasmic_color_type.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import "./plasmic_canvas_app_explorer.css"; // plasmic-import: mXv5TZ5SUPGRneH9RoMn6q/projectcss
import "./PlasmicRatings.css"; // plasmic-import: kZJnDl5cN7jJ7/css
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: nqfHwTpPv2XFpy/icon

export const PlasmicRatings__VariantProps = new Array("stars");

export const PlasmicRatings__ArgProps = new Array("numReviews");

function PlasmicRatings__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        "plasmic_default__all",
        "plasmic_default__div",
        "root_reset_mXv5TZ5SUPGRneH9RoMn6q",
        "plasmic_default_styles",
        "plasmic_mixins",
        "plasmic_tokens",
        "plasmic_tokens",
        "Ratings__root__pt884",
        {
          Ratings__rootstars_five__pt884KMq9G: hasVariant(
            variants,
            "stars",
            "five"
          ),

          Ratings__rootstars_four__pt884MrnEt: hasVariant(
            variants,
            "stars",
            "four"
          ),

          Ratings__rootstars_one__pt884WJukp: hasVariant(
            variants,
            "stars",
            "one"
          ),

          Ratings__rootstars_three__pt884IroP7: hasVariant(
            variants,
            "stars",
            "three"
          ),

          Ratings__rootstars_two__pt884Hd5FG: hasVariant(
            variants,
            "stars",
            "two"
          ),

          Ratings__rootstars_zero__pt884MxU6I: hasVariant(
            variants,
            "stars",
            "zero"
          )
        }
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(
          "plasmic_default__all",
          "plasmic_default__div",
          "Ratings__freeBox__izHFx"
        )}
      >
        {(hasVariant(variants, "stars", "zero") ? false : true) ? (
          <StarIcon
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__svg",
              "Ratings__svg__cBbLv",
              {
                Ratings__svgstars_five__cBbLvkMq9G: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                Ratings__svgstars_zero__cBbLvMxU6I: hasVariant(
                  variants,
                  "stars",
                  "zero"
                )
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__svg",
              "Ratings__svg__hEl5P",
              {
                Ratings__svgstars_five__hEl5PkMq9G: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                Ratings__svgstars_four__hEl5PMrnEt: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                Ratings__svgstars_one__hEl5PwJukp: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                Ratings__svgstars_three__hEl5PiroP7: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                Ratings__svgstars_two__hEl5PHd5FG: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                Ratings__svgstars_zero__hEl5PMxU6I: hasVariant(
                  variants,
                  "stars",
                  "zero"
                )
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__svg",
              "Ratings__svg___42Gi3",
              {
                Ratings__svgstars_five___42Gi3KMq9G: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                Ratings__svgstars_four___42Gi3MrnEt: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                Ratings__svgstars_one___42Gi3WJukp: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                Ratings__svgstars_three___42Gi3IroP7: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                Ratings__svgstars_two___42Gi3Hd5FG: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                Ratings__svgstars_zero___42Gi3MxU6I: hasVariant(
                  variants,
                  "stars",
                  "zero"
                )
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__svg",
              "Ratings__svg__sMn3L",
              {
                Ratings__svgstars_five__sMn3LKMq9G: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                Ratings__svgstars_four__sMn3LMrnEt: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                Ratings__svgstars_one__sMn3LwJukp: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                Ratings__svgstars_three__sMn3LiroP7: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                Ratings__svgstars_two__sMn3LHd5FG: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                Ratings__svgstars_zero__sMn3LMxU6I: hasVariant(
                  variants,
                  "stars",
                  "zero"
                )
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__svg",
              "Ratings__svg__byyuC",
              {
                Ratings__svgstars_five__byyuCkMq9G: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                Ratings__svgstars_four__byyuCMrnEt: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                Ratings__svgstars_one__byyuCwJukp: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                Ratings__svgstars_three__byyuCiroP7: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                Ratings__svgstars_two__byyuCHd5FG: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                Ratings__svgstars_zero__byyuCMxU6I: hasVariant(
                  variants,
                  "stars",
                  "zero"
                )
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? true
            : false
        ) ? (
          <StarIcon
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__svg",
              "Ratings__svg__deMyc",
              {
                Ratings__svgstars_five__deMycKMq9G: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                Ratings__svgstars_four__deMycMrnEt: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                Ratings__svgstars_one__deMycwJukp: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                Ratings__svgstars_three__deMyciroP7: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                Ratings__svgstars_two__deMycHd5FG: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                Ratings__svgstars_zero__deMycMxU6I: hasVariant(
                  variants,
                  "stars",
                  "zero"
                )
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__svg",
              "Ratings__svg___7RqGi",
              {
                Ratings__svgstars_five___7RqGikMq9G: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                Ratings__svgstars_four___7RqGiMrnEt: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                Ratings__svgstars_three___7RqGIiroP7: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                Ratings__svgstars_two___7RqGiHd5FG: hasVariant(
                  variants,
                  "stars",
                  "two"
                )
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__svg",
              "Ratings__svg__dzAub",
              {
                Ratings__svgstars_five__dzAubKMq9G: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                Ratings__svgstars_four__dzAubMrnEt: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                Ratings__svgstars_three__dzAubiroP7: hasVariant(
                  variants,
                  "stars",
                  "three"
                )
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__svg",
              "Ratings__svg__ip6Iz",
              {
                Ratings__svgstars_five__ip6IzKMq9G: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                Ratings__svgstars_four__ip6IzMrnEt: hasVariant(
                  variants,
                  "stars",
                  "four"
                )
              }
            )}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? false : true) ? (
          <StarIcon
            className={classNames(
              "plasmic_default__all",
              "plasmic_default__svg",
              "Ratings__svg__dwVrb",
              {
                Ratings__svgstars_five__dwVrbKMq9G: hasVariant(
                  variants,
                  "stars",
                  "five"
                )
              }
            )}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames("Ratings__slotTargetNumReviews__wb8KQ")
      })}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps
    });

    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
