# Generated by Django 3.2.5 on 2021-07-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='ltitool',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='canvas_app_explorer.LogoImage/bytes/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='ltitool',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='canvas_app_explorer.MainImage/bytes/filename/mimetype'),
        ),
    ]
