# Generated by Django 3.2.8 on 2021-10-12 17:25

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0003_auto_20210803_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltitool',
            name='long_description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='ltitool',
            name='privacy_agreement',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='ltitool',
            name='short_description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='ltitool',
            name='support_resources',
            field=django_quill.fields.QuillField(),
        ),
    ]
