# Generated by Django 3.2.13 on 2022-04-11 19:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0005_adding_mysql_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltitool',
            name='short_description',
            field=tinymce.models.HTMLField(max_length=120),
        ),
    ]
