# Generated by Django 3.2.13 on 2022-04-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0006_alter_ltitool_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='logo_image_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ltitool',
            name='main_image_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
