# Generated by Django 3.2.13 on 2022-05-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0007_auto_20220420_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='canvas_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
