# Generated by Django 3.2.13 on 2022-06-23 15:26

# Resource(s):
# - https://docs.djangoproject.com/en/4.0/topics/migrations/#data-migrations
# - https://lti.colcampus.com/xml_builder

from django.db import migrations


PLACEMENT_NAMES = [
    'Account Navigation',
    'Assignment Configuration',
    'Assignment Menu',
    'Assignment Selection',
    'Collaboration',
    'Course Home Sub Navigation',
    'Course Navigation',
    'Course Settings Sub Navigation',
    'Discussion Menu',
    'Editor Button',
    'File Menu',
    'Global Navigation',
    'Homework Submission',
    'Link Selection',
    'Migration Selection',
    'Module Menu',
    'Post Grades',
    'Quiz Menu',
    'Tool Configuration',
    'User Navigation',
    'Wiki Page Menu'
]


def create_initial_canvas_placements(apps, schema_editor) -> None:
    CanvasPlacement = apps.get_model('canvas_app_explorer', 'CanvasPlacement')
    CanvasPlacement.objects.bulk_create([
        CanvasPlacement(name=placement_name) for placement_name in PLACEMENT_NAMES
    ])


def reverse_canvas_placement_creation(apps, schema_editor) -> None:
    CanvasPlacement = apps.get_model('canvas_app_explorer', 'CanvasPlacement')
    CanvasPlacement.objects.filter(name__in=PLACEMENT_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0008_ltitool_canvas_id'),
    ]

    operations = [
        migrations.RunPython(create_initial_canvas_placements, reverse_canvas_placement_creation),
    ]
