# Generated by Django 3.2.13 on 2022-06-23 15:26

# Resource(s):
# - https://docs.djangoproject.com/en/4.0/topics/migrations/#data-migrations
# - https://canvas.instructure.com/doc/api/file.tools_intro.html

from django.db import migrations


PLACEMENT_NAMES = [
    'Account Navigation',
    'Assignment Selection',
    'Collaboration',
    'Course Navigation',
    'Editor Button',
    'Homework Submission',
    'Link Selection',
    'Migration Selection',
    'User Navigation'
]

def create_initial_canvas_placements(apps, schema_editor) -> None:
    CanvasPlacement = apps.get_model('canvas_app_explorer', 'CanvasPlacement')
    CanvasPlacement.objects.bulk_create([
        CanvasPlacement(name=placement_name) for placement_name in PLACEMENT_NAMES
    ])


def reverse_canvas_placement_creation(apps, schema_editor) -> None:
    CanvasPlacement = apps.get_model('canvas_app_explorer', 'CanvasPlacement')
    CanvasPlacement.objects.filter(name__in=PLACEMENT_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0008_ltitool_canvas_id'),
    ]

    operations = [
        migrations.RunPython(create_initial_canvas_placements, reverse_canvas_placement_creation),
    ]
