# Generated by Django 3.2.14 on 2022-08-02 18:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0010_alter_ltitool_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='metadata',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
