# Generated by Django 3.2.15 on 2022-10-13 21:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0011_ltitool_internal_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltitool',
            name='internal_notes',
            field=tinymce.models.HTMLField(blank=True, help_text='a place to put helpful info for admins, not visible to users', null=True),
        ),
    ]
