# Generated by Django 3.2.15 on 2023-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0012_alter_ltitool_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltitool',
            name='is_public',
            field=models.BooleanField(default=False, help_text='true if the tool is visible to users'),
        ),
    ]
