apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  variant: dev
  org: umich
nameSuffix: -dev
bases:
- ../../base
configMapGenerator:
  - name: canvas-app-explorer
    behavior: replace
    envs:
    - secret/configmap-dev.properties